version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6
    container_name: edubridge-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: edubridge
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - edubridge-network

  # Backend Server
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: edubridge-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:admin123@mongodb:27017/edubridge?authSource=admin
      JWT_SECRET: your-secret-key-change-in-production
      FIREBASE_PROJECT_ID: your-firebase-project-id
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - edubridge-network

  # Frontend Client
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: edubridge-client
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - edubridge-network

networks:
  edubridge-network:
    driver: bridge

volumes:
  mongodb_data:
