### student login
POST http://localhost:1544/student/login
Content-Type: application/json

{
    "studentID": "22071A3255",
    "password": "Welcome@123"
}

### Update Student Profile
### Update Student Academic Data
PUT http://localhost:1544/student/academic/22071A3255
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZGE5Nzc1NzdjNjI3ZWU3OWExZDU0MyIsInJvbGUiOiJzdHVkZW50IiwiZW1haWwiOiJiaGFyZ2F2dHR5bEBnbWFpbC5jb20iLCJpYXQiOjE3NDI4MTA5MDAsImV4cCI6MjAwMjAxMDkwMH0.vmUq30PZgZCuDJt0rs_46XORbQxibTdGRw5EmiRvZnU

{
  "campus": "VNR VJIET",
  "batch": "2022-2026",
  "department": "CSBS",
  "degree": "B.Tech",
  "tenth": "90.1",
  "twelfth": "97.3",
  "diploma": "NA",
  "underGraduate": "9.45",
  "postGraduate": "NA"
}
###

GET http://localhost:1544/student/academic/22071A3255
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZGE5Nzc1NzdjNjI3ZWU3OWExZDU0MyIsInJvbGUiOiJzdHVkZW50IiwiZW1haWwiOiIyMjA3MUEzMjU1QHZucnZqaWV0LmluIiwiaWF0IjoxNzQyNTc0MzgxLCJleHAiOjIwMDE3NzQzODF9.Qz7a3JQ_H1VHu4LZKTyunu2G66twCd4nQ2_jxqUAuj0

###
PUT http://localhost:1544/student/additional/22071A3255
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZGE5Nzc1NzdjNjI3ZWU3OWExZDU0MyIsInJvbGUiOiJzdHVkZW50IiwiZW1haWwiOiIyMjA3MUEzMjU1QHZucnZqaWV0LmluIiwiaWF0IjoxNzQyNTc0MzgxLCJleHAiOjIwMDE3NzQzODF9.Qz7a3JQ_H1VHu4LZKTyunu2G66twCd4nQ2_jxqUAuj0

{
  "backlogsHistory": "No",
  "currentBacklogs": "0",
  "interestedInPlacement": "Yes",
  "skills": "Node.js, React",
  "languages": "English, Hindi, Telugu"
}

###
GET http://localhost:1544/student/additional/22071A3255
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZGE5Nzc1NzdjNjI3ZWU3OWExZDU0MyIsInJvbGUiOiJzdHVkZW50IiwiZW1haWwiOiIyMjA3MUEzMjU1QHZucnZqaWV0LmluIiwiaWF0IjoxNzQyNTc0MzgxLCJleHAiOjIwMDE3NzQzODF9.Qz7a3JQ_H1VHu4LZKTyunu2G66twCd4nQ2_jxqUAuj0

###
PUT http://localhost:1544/student/personal/22071A3255
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZGE5Nzc1NzdjNjI3ZWU3OWExZDU0MyIsInJvbGUiOiJzdHVkZW50IiwiZW1haWwiOiIyMjA3MUEzMjU1QHZucnZqaWV0LmluIiwiaWF0IjoxNzQyNTc0MzgxLCJleHAiOjIwMDE3NzQzODF9.Qz7a3JQ_H1VHu4LZKTyunu2G66twCd4nQ2_jxqUAuj0

{
  "name": "Bhargav Tammana",
  "studentID": "22071A3255",
  "email": "bhargav@example.com",
  "phone": "9876543210",
  "gender": "Male",
  "dateOfBirth": "2003-05-12"
}
###

GET http://localhost:1544/student/dashBoard/22071A3255
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZGE5Nzc1NzdjNjI3ZWU3OWExZDU0MyIsInJvbGUiOiJzdHVkZW50IiwiZW1haWwiOiIyMjA3MUEzMjU1QHZucnZqaWV0LmluIiwiaWF0IjoxNzQyNTc0MzgxLCJleHAiOjIwMDE3NzQzODF9.Qz7a3JQ_H1VHu4LZKTyunu2G66twCd4nQ2_jxqUAuj0

###
GET http://localhost:1544/student/activeWorks/22071A3255
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZGE5Nzc1NzdjNjI3ZWU3OWExZDU0MyIsInJvbGUiOiJzdHVkZW50IiwiZW1haWwiOiIyMjA3MUEzMjU1QHZucnZqaWV0LmluIiwiaWF0IjoxNzQyNTc0MzgxLCJleHAiOjIwMDE3NzQzODF9.Qz7a3JQ_H1VHu4LZKTyunu2G66twCd4nQ2_jxqUAuj0

###
GET http://localhost:1544/student/archive/22071A3255
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZGE5Nzc1NzdjNjI3ZWU3OWExZDU0MyIsInJvbGUiOiJzdHVkZW50IiwiZW1haWwiOiIyMjA3MUEzMjU1QHZucnZqaWV0LmluIiwiaWF0IjoxNzQyNTc0MzgxLCJleHAiOjIwMDE3NzQzODF9.Qz7a3JQ_H1VHu4LZKTyunu2G66twCd4nQ2_jxqUAuj0

###
GET http://localhost:1544/student/campusProjects
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZGE5Nzc1NzdjNjI3ZWU3OWExZDU0MyIsInJvbGUiOiJzdHVkZW50IiwiZW1haWwiOiIyMjA3MUEzMjU1QHZucnZqaWV0LmluIiwiaWF0IjoxNzQyNTc0MzgxLCJleHAiOjIwMDE3NzQzODF9.Qz7a3JQ_H1VHu4LZKTyunu2G66twCd4nQ2_jxqUAuj0

### File Upload
POST http://localhost:1544/files/upload
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZGE5Nzc1NzdjNjI3ZWU3OWExZDU0MyIsInJvbGUiOiJzdHVkZW50IiwiZW1haWwiOiIyMjA3MUEzMjU1QHZucnZqaWV0LmluIiwiaWF0IjoxNzQyNTc0MzgxLCJleHAiOjIwMDE3NzQzODF9.Qz7a3JQ_H1VHu4LZKTyunu2G66twCd4nQ2_jxqUAuj0
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="pdf"; filename="Bhargav_CV.pdf"
Content-Type: application/pdf

< "C:\Users\bharg\OneDrive\Desktop\Bhargav_CV Experienced.pdf"
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="studentID"

22071A3255
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="projectID"

PROJ123
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Get File Metadata
GET http://localhost:1544/files/metadata/67e4257c324009b3bcdee819
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZGE5Nzc1NzdjNjI3ZWU3OWExZDU0MyIsInJvbGUiOiJzdHVkZW50IiwiZW1haWwiOiIyMjA3MUEzMjU1QHZucnZqaWV0LmluIiwiaWF0IjoxNzQyNTc0MzgxLCJleHAiOjIwMDE3NzQzODF9.Qz7a3JQ_H1VHu4LZKTyunu2G66twCd4nQ2_jxqUAuj0

### Download File
GET http://localhost:1544/files/download/22071A3262
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZGE5Nzc1NzdjNjI3ZWU3OWExZDU0MyIsInJvbGUiOiJzdHVkZW50IiwiZW1haWwiOiIyMjA3MUEzMjU1QHZucnZqaWV0LmluIiwiaWF0IjoxNzQyNTc0MzgxLCJleHAiOjIwMDE3NzQzODF9.Qz7a3JQ_H1VHu4LZKTyunu2G66twCd4nQ2_jxqUAuj0

### Delete File
DELETE http://localhost:1544/files/67e41cfbe11806c243cff220
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZGE5Nzc1NzdjNjI3ZWU3OWExZDU0MyIsInJvbGUiOiJzdHVkZW50IiwiZW1haWwiOiIyMjA3MUEzMjU1QHZucnZqaWV0LmluIiwiaWF0IjoxNzQyNTc0MzgxLCJleHAiOjIwMDE3NzQzODF9.Qz7a3JQ_H1VHu4LZKTyunu2G66twCd4nQ2_jxqUAuj0

###
GET http://localhost:1544/files/resume/22071A3262
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZGE5Nzc1NzdjNjI3ZWU3OWExZDU0MyIsInJvbGUiOiJzdHVkZW50IiwiZW1haWwiOiIyMjA3MUEzMjU1QHZucnZqaWV0LmluIiwiaWF0IjoxNzQyNTc0MzgxLCJleHAiOjIwMDE3NzQzODF9.Qz7a3JQ_H1VHu4LZKTyunu2G66twCd4nQ2_jxqUAuj0
